volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  neo4j_import:

services:
  neo4j:
    image: neo4j:community
    container_name: neo4j
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/var/lib/neo4j/import
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt Protocol (for queries)
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
